EVENTS_LIST = [
    (1, 1, 'National Hobby Month'),
    (1, 2, 'World Introvert Day'),
    (1, 3, 'Savitribai Phule Jayanti'),
    (1, 5, 'National Whipped Cream Day'),
    (1, 6, 'National Bean Day'),
    (1, 7, 'Orthodox Christmas'),
    (1, 12, 'National Youth Day'),
    (1, 13, 'Lohri'),
    (1, 14, 'Makar Sankranti'),
    (1, 15, 'Pongal'),
    (1, 16, 'International Hot and Spicy Food Day'),
    (1, 18, 'World Religion Day'),
    (1, 19, 'National Popcorn Day'),
    (1, 20, 'National Penguin Day'),
    (1, 23, 'National Handwriting Day'),
    (1, 24, 'National Girl Child Day'),
    (1, 25, 'National Tourism Day'),
    (1, 26, 'Republic Day'),
    (1, 29, 'Lunar New Year'),
    (1, 30, "Martyrs' Day (Shaheed Diwas)"),
    (1, 31, 'National Hot Chocolate Day'),
    (2, 1, 'Kick Day'),
    (2, 2, 'Groundhog Day 2025'),
    (2, 3, 'Vasant Panchami'),
    (2, 4, 'Rosa Parks Day'),
    (2, 6, 'National Chopsticks Day'),
    (2, 7, 'Rose Day'),
    (2, 8, 'Propose Day'),
    (2, 9, 'Chocolate Day'),
    (2, 10, 'Teddy Day'),
    (2, 11, 'Promise Day'),
    (2, 12, 'Hug Day'),
    (2, 13, 'Kiss Day'),
    (2, 14, "Valentine's Day"),
    (2, 15, 'Slap Day'),
    (2, 17, 'Perfume Day'),
    (2, 18, 'Flirting Day'),
    (2, 19, 'Confession Day'),
    (2, 20, 'Missing Day'),
    (2, 21, 'Breakup Day'),
    (2, 22, 'Maharishi Dayanand Saraswati Jayanti'),
    (2, 25, 'National Clam Chowder Day'),
    (2, 26, 'Maha Shivratri'),
    (2, 28, 'National Science Day'),
    (3, 1, 'International Ideas Month'),
    (3, 3, 'World Wildlife Day'),
    (3, 4, 'Organize Your Home Office Day'),
    (3, 5, 'International Day for Disarmament and Non-Proliferation Awareness'),
    (3, 6, 'National Dentists Day'),
    (3, 7, 'National Cereal Day'),
    (3, 8, 'International Fanny Pack Day'),
    (3, 12, 'Dandi March'),
    (3, 13, 'Holika Dahan'),
    (3, 14, 'Holi'),
    (3, 15, 'Durga Puja'),
    (3, 16, 'National Poison Prevention Week'),
    (3, 19, 'Certified Nurses Day'),
    (3, 20, 'International Day of Happiness'),
    (3, 21, 'World Poetry Day'),
    (3, 22, 'World Water Day'),
    (3, 23, 'World Meteorological Day'),
    (3, 24, 'World Tuberculosis Day'),
    (3, 27, 'International Whiskey Day'),
    (3, 30, 'Gudi Padwa'),
    (4, 1, "April Fool's Day"),
    (4, 2, 'National Walking Day'),
    (4, 3, 'World Party Day'),
    (4, 4, 'World Rat Day'),
    (4, 5, 'International Pillow Fight Day'),
    (4, 6, 'National Student-Athlete Day'),
    (4, 7, 'Ram Navami'),
    (4, 9, 'National Name Yourself Day'),
    (4, 10, 'World Homeopathy Day'),
    (4, 11, 'National Submarine Day'),
    (4, 12, 'Hanuman Jayanti'),
    (4, 13, 'Palm Sunday'),
    (4, 14, 'Ambedkar Jayanti'),
    (4, 15, 'World Art Day'),
    (4, 16, 'World Voice Day'),
    (4, 17, 'Blah Blah Blah Day'),
    (4, 18, 'World Heritage Day'),
    (4, 19, 'Husband Appreciation Day'),
    (4, 20, 'Easter Sunday'),
    (4, 21, 'International Creativity and Innovation Day'),
    (4, 22, 'International Mother Earth Day'),
    (4, 23, 'World Book Day'),
    (4, 24, 'National Panchayati Raj Day'),
    (4, 25, 'National Telephone Day'),
    (4, 26, 'International Sculpture Day'),
    (4, 29, 'International Dance Day'),
    (4, 30, 'Honesty Day'),
    (5, 1, 'World Password Day'),
    (5, 2, 'International Harry Potter Day'),
    (5, 3, 'Astronomy Day'),
    (5, 4, 'World Laughter Day'),
    (5, 9, 'Maharana Pratap Jayanti'),
    (5, 10, 'National Shrimp Day'),
    (5, 11, "Mother's Day"),
    (5, 12, 'International Women in Mathematics Day'),
    (5, 15, 'National Chocolate Chip Day'),
    (5, 18, 'International Museum Day'),
    (5, 21, 'International Tea Day'),
    (5, 22, 'International Day for Biological Diversity'),
    (5, 23, 'World Turtle Day'),
    (5, 25, 'Towel Day'),
    (5, 26, 'Vat Savitri'),
    (5, 27, 'Shani Jayanti'),
    (5, 28, 'Menstrual Hygiene Day'),
    (5, 31, 'World No Tobacco Day'),
    (6, 1, 'Global Day of Parents'),
    (6, 2, 'Leave The Office Early Day'),
    (6, 3, 'World Bicycle Day'),
    (6, 5, 'World Environment Day'),
    (6, 6, 'D-Day Anniversary'),
    (6, 7, 'World Food Safety Day'),
    (6, 8, 'National Best Friends Day'),
    (6, 11, 'Kabir Jayanti'),
    (6, 12, 'World Day Against Child Labor'),
    (6, 13, 'International Albinism Awareness Day'),
    (6, 14, 'World Blood Donor Day'),
    (6, 15, "Father's Day"),
    (6, 18, 'International Panic Day'),
    (6, 19, 'World Sauntering Day'),
    (6, 21, 'Go Skateboarding Day'),
    (6, 22, 'World Rainforest Day'),
    (6, 23, 'Apara Ekadashi'),
    (6, 26, 'Muharram'),
    (6, 27, 'International Pineapple Day'),
    (6, 29, 'National Camera Day'),
    (6, 30, 'World Social Media Day'),
    (7, 1, 'International Joke Day'),
    (7, 2, 'World UFO Day'),
    (7, 3, 'St Thomas Day'),
    (7, 5, 'Dree Festival'),
    (7, 6, 'Devshayani Ekadashi'),
    (7, 7, 'Global Forgiveness Day'),
    (7, 11, 'World Population Day'),
    (7, 12, 'National Simplicity Day'),
    (7, 16, 'World Snake Day'),
    (7, 17, 'World Emoji Day'),
    (7, 18, 'Nelson Mandela International Day'),
    (7, 20, 'National Moon Day'),
    (7, 22, 'National Mango Day'),
    (7, 23, 'Sawan Shivratri'),
    (7, 24, 'International Self Care Day'),
    (7, 26, 'Uncle and Aunt Day'),
    (7, 27, "Parents' Day"),
    (7, 29, 'International Tiger Day'),
    (7, 30, 'International Friendship Day'),
    (8, 3, "Sisters' Day"),
    (8, 6, 'Hiroshima Day'),
    (8, 9, 'Raksha Bandhan'),
    (8, 12, 'International Youth Day'),
    (8, 14, 'World Lizard Day'),
    (8, 15, 'Independence Day'),
    (8, 16, 'Janmashtami'),
    (8, 19, 'World Photography Day'),
    (8, 21, 'Senior Citizens Day'),
    (8, 22, 'Be An Angel Day'),
    (8, 23, 'International Day for the Remembrance of the Slave Trade and its Abolition'),
    (8, 24, 'Pluto Demoted Day'),
    (8, 27, 'Ganesh Chaturthi'),
    (8, 30, 'National Beach Day'),
    (8, 31, 'Radhashtami'),
    (9, 4, 'National Wildlife Day'),
    (9, 5, 'National Food Bank Day'),
    (9, 6, 'Ananta Chaturdashi'),
    (9, 8, 'Pardon Day'),
    (9, 9, 'National Teddy Bear Day'),
    (9, 12, 'National Video Games Day'),
    (9, 13, 'International Chocolate Day'),
    (9, 14, 'Hindi DIwas'),
    (9, 15, "Engineer's Day"),
    (9, 17, 'International Country Music Day'),
    (9, 18, 'International Equal Pay Day'),
    (9, 21, 'World Gratitude Day'),
    (9, 22, 'Navratri'),
    (9, 24, 'World Gorilla Day'),
    (9, 25, 'World Pharmacist Day'),
    (9, 26, 'World Contraception Day'),
    (9, 27, 'World Tourism Day'),
    (10, 1, 'International Music Day'),
    (10, 2, 'Gandhi Jayanti'),
    (10, 3, 'World Smile Day'),
    (10, 4, 'World Animal Day'),
    (10, 5, 'World Teachers’ Day'),
    (10, 6, 'World Architecture Day'),
    (10, 7, 'World Cotton Day'),
    (10, 8, 'Indian Air Force Day'),
    (10, 9, 'World Post Day'),
    (10, 10, 'Karwa Chauth'),
    (10, 15, 'Global Handwashing Day'),
    (10, 16, 'World Food Day'),
    (10, 17, 'International Day for the Eradication of Poverty'),
    (10, 18, 'Dhanteras'),
    (10, 20, 'Kali Puja'),
    (10, 21, 'Diwali'),
    (10, 22, 'Lakshmi Puja'),
    (10, 23, 'Bhai Dooj'),
    (10, 24, 'United Nations Day'),
    (10, 28, 'Chhath Puja'),
    (10, 29, 'Jagaddhatri Puja'),
    (10, 31, 'Halloween'),
    (11, 1, 'No Shave November'),
    (11, 2, "All Souls' Day"),
    (11, 3, 'Recreation Day'),
    (11, 4, 'Melbourne Cup'),
    (11, 5, 'Guru Nanak Jayanti'),
    (11, 10, 'International Accounting Day'),
    (11, 11, 'Singles Day'),
    (11, 12, 'World Pneumonia Day'),
    (11, 13, 'World Kindness Day'),
    (11, 14, "Children's Day"),
    (11, 16, 'International Day for Tolerance'),
    (11, 18, "National Entrepreneurs' Day"),
    (11, 19, "International Men's Day"),
    (11, 20, 'World Philosophy Day'),
    (11, 21, 'World Television Day'),
    (11, 25, 'International Day for the Elimination of Violence Against Women'),
    (11, 26, 'National Milk Day'),
    (11, 27, 'Thanksgiving Day'),
    (12, 4, 'Wildlife Conservation Day'),
    (12, 5, 'World Soil Day'),
    (12, 6, 'Mahaparinirvan Din'),
    (12, 7, 'National Cotton Candy Day'),
    (12, 8, 'National Brownie Day'),
    (12, 9, 'National Pastry Day'),
    (12, 11, 'International Mountain Day'),
    (12, 14, 'Monkey Day'),
    (12, 21, 'Winter Solstice'),
    (12, 23, 'National Farmers Day'),
    (12, 24, 'Christmas Eve'),
    (12, 25, 'Christmas'),
    (12, 26, 'Boxing Day'),
    (12, 27, 'International Day of Epidemic Preparedness'),
    (12, 31, "New Year's Eve")
]
